### ISSUE TITLE
From method proposal

### ISSUE THREAD

**Issue by paganotoni** [duffn/name#1]
Hi Duffn 👋, 

I was using your library this weekend and thought of an idea that i would like to present to you, and if you don't have the bandwidth i'm willing to put together a PR.

My idea is to have a function inside the library called `NameFrom` that will receive an interface{} and return a name.Name, something like:

```
From(person interface{}) (Name, error)
```

This function will return a name from any struct, to do so it will check that:
-  Passed person is a struct
-  It has FirstName and LastName fields

If so, it will create a Name instance with those field values and then library users could do something like:

```
n, _ := name.From(contact)
if (err != nil ){
 ...
}

n.FullName()
```

Thanks for taking the time to build this lib, and for reading until here.

**Comment by paganotoni** [comment]
Another option would be to have an interface like:

**Comment by duffn** [comment]
Hey @paganotoni! If you'd like to submit a PR, that would be great.
